### ISSUE TITLE
problem in an async tkinter app  'PhotoImage' object has no attribute '_PhotoImage__photo'

### ISSUE THREAD

**Issue by alireza787b** [TomSchimansky/TkinterMapView#37]
I exactly followed your example codes but not working inside my async Tkinter app... you example files works fine but don't working inside my app... is there a compatibility problem with async_tkinter_loop?

This is how I add your widget just after my other widgets
`map_widget = tkintermapview.TkinterMapView(root, width=200, height=200, corner_radius=0)
map_widget.pack()
map_widget.set_position(48.860381, 2.338594)  # Paris, France
map_widget.set_zoom(15)`

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PIL/ImageTk.py", line 146, in __del__
    name = self.__photo.name
AttributeError: 'PhotoImage' object has no attribute '_PhotoImage__photo'
Exception ignored in: <function PhotoImage.__del__ at 0x7f831923b0e0>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PIL/ImageTk.py", line 146, in __del__
    name = self.__photo.name
AttributeError: 'PhotoImage' object has no attribute '_PhotoImage__photo'
Exception ignored in: <function PhotoImage.__del__ at 0x7f831923b0e0>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PIL/ImageTk.py", line 146, in __del__
    name = self.__photo.name
AttributeError: 'PhotoImage' object has no attribute '_PhotoImage__photo'
Exception ignored in: <function PhotoImage.__del__ at 0x7f831923b0e0>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PIL/ImageTk.py", line 146, in __del__
    name = self.__photo.name
AttributeError: 'PhotoImage' object has no attribute '_PhotoImage__photo'
Exception ignored in: <function PhotoImage.__del__ at 0x7f831923b0e0>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PIL/ImageTk.py", line 146, in __del__
    name = self.__photo.name
AttributeError: 'PhotoImage' object has no attribute '_PhotoImage__photo'
Exception ignored in: <function PhotoImage.__del__ at 0x7f831923b0e0>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PIL/ImageTk.py", line 146, in __del__
    name = self.__photo.name
AttributeError: 'PhotoImage' object has no attribute '_PhotoImage__photo'
Exception ignored in: <function PhotoImage.__del__ at 0x7f831923b0e0>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PIL/ImageTk.py", line 146, in __del__
    name = self.__photo.name
AttributeError: 'PhotoImage' object has no attribute '_PhotoImage__photo'
Exception ignored in: <function PhotoImage.__del__ at 0x7f831923b0e0>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PIL/ImageTk.py", line 146, in __del__
    name = self.__photo.name
AttributeError: 'PhotoImage' object has no attribute '_PhotoImage__photo'
Exception ignored in: <function PhotoImage.__del__ at 0x7f831923b0e0>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PIL/ImageTk.py", line 146, in __del__
    name = self.__photo.name
AttributeError: 'PhotoImage' object has no attribute '_PhotoImage__photo'
Exception ignored in: <function PhotoImage.__del__ at 0x7f831923b0e0>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PIL/ImageTk.py", line 146, in __del__
    name = self.__photo.name
AttributeError: 'PhotoImage' object has no attribute '_PhotoImage__photo'

**Comment by TomSchimansky** [comment]
Can you post a full example? I have never used async with tkinter and I don't know what you are doing...

**Comment by alireza787b** [comment]
> Can you post a complete example? I have never used async with Tkinter and I don't know what you are doing...

This might not be the best optimum code, actually my first python experience :)
But this program completely works OK. Only mapview doesn't work as expected.

`import asyncio
from tkinter import *
from async_tkinter_loop import async_handler, async_mainloop
from mavsdk import System
import tkintermapview 


drone = System()
    

async def setup():
    """
    General configurations, setups, and connections are done here.
    :return:
    """

    await drone.connect(system_address="udp://:"+portIn.get())

    printPxh("Waiting for drone to connect...")
    async for state in drone.core.connection_state():
        if state.is_connected:
            printPxh(f"-- Connected to drone!")
            break


    printPxh("Waiting for drone to have a global position estimate...")
    global health
    async for health in drone.telemetry.health():
        if health.is_global_position_ok and health.is_home_position_ok:
            printPxh("-- Global position estimate OK")
            break
    asyncio.ensure_future(print_battery(drone))
    asyncio.ensure_future(print_gps_info(drone))
    asyncio.ensure_future(print_in_air(drone))
    asyncio.ensure_future(print_position(drone))
    asyncio.ensure_future(print_home(drone))
    asyncio.ensure_future(printPxh(msg))
    
    
    
async def takeoff(alt=10):

    printPxh("-- Arming")
    await drone.action.arm()
    printPxh("-- Taking off")
    await drone.action.set_takeoff_altitude(int(altIn.get()))
    await drone.action.takeoff()


async def land():
    printPxh("-- Landing")
    await drone.action.land()

async def changeAlt():
    #async for homepos in drone.telemetry.home():
        #absolute_altitude = homepos.absolute_altitude_m
        #printPxh(homepos)
       # print(absolute_altitude)
        #break
    # async for position in drone.telemetry.position():
    #     curPos = position
    #     break

    homeAlt = homepos.absolute_altitude_m
    flying_alt = homeAlt + int(altIn.get())
    #print(flying_alt)
    # goto_location() takes Absolute MSL altitude
    printPxh("-- Changing Altitude to "+ altIn.get() )

    await drone.action.goto_location(position.latitude_deg, position.longitude_deg , flying_alt, 0)

async def changeYaw():
    
    # async for position in drone.telemetry.position():
    #     curPos = position
    #     break
    #print(flying_alt)
    # goto_location() takes Absolute MSL altitude
    printPxh("-- Changing Yaw to "+ yawIn.get() )

    await drone.action.goto_location(position.latitude_deg, position.longitude_deg , position.absolute_altitude_m, int(yawIn.get()))


def printPxh(msg):
    # pxhOut.delete(1.0,END)
    pxhOut.insert(END, msg + '\n')
    print(msg)
    pxhOut.see("end")

async def print_home(drone):
    global homepos
    async for homepos in drone.telemetry.home():
        # printPxh(f"Home: {homepos.absolute_altitude_m}")
        pass
        #absolute_altitude = homepos.absolute_altitude_m
        #printPxh(homepos)
       # print(absolute_altitude)     
     
        
async def print_battery(drone):
    global battery
    async for battery in drone.telemetry.battery():
        # printPxh(f"Battery: {battery.remaining_percent}")
        pass


async def print_gps_info(drone):
    global gps_info
    async for gps_info in drone.telemetry.gps_info():
        # printPxh(f"GPS info: {gps_info}")
        pass

async def print_in_air(drone):
    global in_air
    async for in_air in drone.telemetry.in_air():
        # printPxh(f"In air: {in_air}")
        pass


async def print_position(drone):
    global position
    async for position in drone.telemetry.position():
        # printPxh("Position: "+position)
        pass



root = Tk()
root.geometry("1280x720")
label = Label(root)
label.pack()

defPort = StringVar(root, value='14540')
portIn = Entry(root, textvariable=defPort)
portIn.pack()
Button(root, text="Connect", command=async_handler(setup)).pack()
# TextBox Creation
defAlt = StringVar(root, value='5')
altIn = Entry(root, textvariable=defAlt)
altIn.pack()
Button(root, text="Take-Off", command=async_handler(takeoff)).pack()
#print(altIn.get())
Button(root, text="Change Altitude", command=async_handler(changeAlt)).pack()
defYaw = StringVar(root, value='0')
yawIn = Entry(root, textvariable=defYaw)
yawIn.pack()
Button(root, text="Change Yaw", command=async_handler(changeYaw)).pack()
Button(root, text="Land", command=async_handler(land)).pack()



# map_widget = tkintermapview.TkinterMapView(root, width=200, height=200, corner_radius=0)
# map_widget.pack()
# map_widget.set_position(48.860381, 2.338594)  # Paris, France
# map_widget.set_zoom(15)

pxhOut = Text(
    root,
    height=20,
    width=100
)
pxhOut.pack(expand=True)
pxhOut.insert(END,"Drone state will be shown here..."+ '\n')
# pxhOut.config(state=DISABLED)

async_mainloop(root)
`

**Comment by alireza787b** [comment]
any update on this issue? I still have this problem

**Comment by abionics** [comment]
I have the same problem

**Comment by vargaaronR** [comment]
I have this problem when I hit the 'Q' or 'W' button in the searching field

**Comment by wchupp** [comment]
this is happening to me every time I close the tkinter window, even with just the example code from the README, no async involved. any updates?

**Comment by EddieRadarHughes** [comment]
I just installed tkintermapview and I get the same error above for all examples here with the exception of the code shown below.   It is the only example I found that runs without errors.    But I will also get the error to appear if I comment out the root_tk.mainloop() line.   I installed using pip3 install tkintermapview on my Windows 10 Pro PC.   Version 1.29 was installed.   I am using Python 3.9 and IDLE.    These scripts provide a stream of the PhotoImage object errors from the startup of the script.    Is there a way to get this to stop?

import tkinter
import tkintermapview
import time

###' create tkinter window
root_tk = tkinter.Tk()
root_tk.geometry(f"{800}x{600}")
root_tk.title("Tkinter MapView")

###' create map widget
map_widget = tkintermapview.TkinterMapView(root_tk, width=800, height=600, corner_radius=0)
map_widget.place(relx=0.5, rely=0.5, anchor=tkinter.CENTER)

root_tk.mainloop()

This is the error I'm getting.   

AttributeError: 'PhotoImage' object has no attribute '_PhotoImage__photo'
Exception ignored in: <function PhotoImage.__del__ at 0x00000154C77141F0>
Traceback (most recent call last):
File "C:\Users\....\ImageTk.py", line 118, in __del__
name = self.__photo.name
