### ISSUE TITLE
Exceptions being raised after latest update

### ISSUE THREAD

**Issue by MaximFilimonovGH** [TomSchimansky/TkinterMapView#67]
Hello.

After updating to the latest version, I started noticing exceptions being raised.

```
Exception ignored in: <function CanvasTile.__del__ at 0x00000229A0918040>
Exception ignored in: <function CanvasTile.__del__ at 0x00000229A0918040>
Traceback (most recent call last):
Exception ignored in: <function CanvasTile.__del__ at 0x00000229A0918040>
Traceback (most recent call last):
Exception ignored in: <function CanvasTile.__del__ at 0x00000229A0918040>
  File "xxx\lib\site-packages\tkintermapview\canvas_tile.py", line 24, in __del__
Traceback (most recent call last):
Traceback (most recent call last):
Exception ignored in: <function CanvasTile.__del__ at 0x00000229A0918040>
Traceback (most recent call last):
  File "xxx\lib\site-packages\tkintermapview\canvas_tile.py", line 24, in __del__
  File "xxx\lib\site-packages\tkintermapview\canvas_tile.py", line 24, in __del__
  File "xxx\lib\site-packages\tkintermapview\canvas_tile.py", line 24, in __del__
  File "xxx\lib\site-packages\tkintermapview\canvas_tile.py", line 24, in __del__
    self.delete()
  File "xxx\lib\site-packages\tkintermapview\canvas_tile.py", line 47, in delete
    self.delete()
  File "xxx\lib\site-packages\tkintermapview\canvas_tile.py", line 47, in delete
    self.delete()
    self.delete()
  File "xxx\lib\site-packages\tkintermapview\canvas_tile.py", line 47, in delete
  File "xxx\lib\site-packages\tkintermapview\canvas_tile.py", line 47, in delete
    self.delete()
  File "xxx\lib\site-packages\tkintermapview\canvas_tile.py", line 47, in delete
    self.map_widget.canvas.delete(self.canvas_object)
    self.map_widget.canvas.delete(self.canvas_object)
  File "xxx\lib\tkinter\__init__.py", line 2852, in delete
    self.map_widget.canvas.delete(self.canvas_object)
    self.map_widget.canvas.delete(self.canvas_object)
  File "xxx\lib\tkinter\__init__.py", line 2852, in delete
    self.map_widget.canvas.delete(self.canvas_object)
  File "xxx\lib\tkinter\__init__.py", line 2852, in delete
  File "xxx\lib\tkinter\__init__.py", line 2852, in delete
  File "xxx\lib\tkinter\__init__.py", line 2852, in delete
    self.tk.call((self._w, 'delete') + args)
_tkinter.TclError: invalid command name ".!ctktoplevel2.!mapframe.!tkintermapview.!canvas"
    self.tk.call((self._w, 'delete') + args)
    self.tk.call((self._w, 'delete') + args)
_tkinter.TclError: invalid command name ".!ctktoplevel2.!mapframe.!tkintermapview.!canvas"
    self.tk.call((self._w, 'delete') + args)
_tkinter.TclError: invalid command name ".!ctktoplevel2.!mapframe.!tkintermapview.!canvas"
_tkinter.TclError: invalid command name ".!ctktoplevel2.!mapframe.!tkintermapview.!canvas"
    self.tk.call((self._w, 'delete') + args)
_tkinter.TclError: invalid command name ".!ctktoplevel2.!mapframe.!tkintermapview.!canvas"
```

Can you please have a look at this?

Thanks!

**Comment by MaximFilimonovGH** [comment]
Seems to be fixed with the latest updates. Thanks!
